# Generated by Django 5.2.13 on 2026-05-07 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('website_url', models.URLField(blank=True)),
                ('rss_url', models.URLField(unique=True)),
                ('category', models.CharField(choices=[('notebook', 'Notebook'), ('hardware', 'Hardware'), ('peripherals', 'Peripherals'), ('general', 'General tech')], default='hardware', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('notes', models.TextField(blank=True)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('notebook', 'Notebook'), ('hardware', 'Hardware'), ('peripherals', 'Peripherals'), ('general', 'General tech')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.newssource')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_newsar_publish_db2481_idx')],
            },
        ),
    ]
