# Generated by Django 5.2.13 on 2026-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='guid',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
