# Generated by Django 5.2.13 on 2026-05-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('brand_name', models.CharField(default='BLAST INFO & TECH', max_length=120)),
                ('visual_identity_manual', models.TextField()),
                ('master_prompt', models.TextField()),
                ('gamer_prompt', models.TextField(blank=True)),
                ('notebook_prompt', models.TextField(blank=True)),
                ('workstation_prompt', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#6E2BC3', max_length=7)),
                ('accent_color', models.CharField(default='#7A22FF', max_length=7)),
                ('dark_color', models.CharField(default='#120018', max_length=7)),
                ('light_color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name': 'Brand guide',
                'verbose_name_plural': 'Brand guides',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
