# Generated by Django 5.2.13 on 2026-04-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BLAST INFO & TECH', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('brand_summary', models.TextField(default='BLAST INFO & TECH produz stories com foco em tecnologia, hardware, IA e cultura digital, sempre com linguagem clara, forte contraste visual e leitura imediata em tela vertical.')),
                ('visual_rules', models.TextField(default='Priorizar composição vertical 9:16, contraste alto, clima editorial-tech, tipografia marcante, elemento principal único e legibilidade suficiente para sobreposição de texto de story.')),
                ('copy_prompt_template', models.TextField(default='Voce esta criando um conceito de Instagram Story para {brand_name}.\n\nGuia da marca:\n{brand_summary}\n\nRegras visuais:\n{visual_rules}\n\nContexto do projeto:\n{project_context}\n\nPedido atual do editor:\n{change_request}\n\nResponda apenas em JSON valido com estas chaves:\n- headline\n- copy_text\n- visual_direction\n- image_prompt\n- generation_notes\n\nO copy_text deve ser conciso, pronto para um unico story, em portugues do Brasil.\n')),
                ('image_prompt_template', models.TextField(default="Crie a arte de um unico story vertical 9:16 para {brand_name}.\n\nGuia da marca:\n{brand_summary}\n\nRegras visuais:\n{visual_rules}\n\nDirecao visual aprovada:\n{visual_direction}\n\nPrompt base da imagem:\n{image_prompt}\n\nPedido atual do editor:\n{change_request}\n\nEvite marcas d'agua, mockups de celular, colagens confusas e texto pequeno ilegivel.\n")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand guide',
                'verbose_name_plural': 'Brand guides',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
