# Generated by Django 5.2.13 on 2026-04-29 19:53

from django.db import migrations, models


def migrate_visual_identity_prompt(apps, schema_editor):
    BrandGuide = apps.get_model('branding', 'BrandGuide')
    for guide in BrandGuide.objects.all():
        parts = [part.strip() for part in [guide.brand_summary, guide.visual_rules] if part and part.strip()]
        if parts:
            guide.visual_identity_prompt = "\n\n".join(parts)

        if guide.copy_prompt_template:
            guide.copy_prompt_template = (
                guide.copy_prompt_template
                .replace('{brand_summary}\n\nRegras visuais:\n{visual_rules}', '{visual_identity_prompt}')
                .replace('{brand_summary}', '{visual_identity_prompt}')
                .replace('{visual_rules}', '{visual_identity_prompt}')
            )

        if guide.image_prompt_template:
            guide.image_prompt_template = (
                guide.image_prompt_template
                .replace('{brand_summary}\n\nRegras visuais:\n{visual_rules}', '{visual_identity_prompt}')
                .replace('{brand_summary}', '{visual_identity_prompt}')
                .replace('{visual_rules}', '{visual_identity_prompt}')
            )

        guide.save(update_fields=['visual_identity_prompt', 'copy_prompt_template', 'image_prompt_template'])


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandguide',
            name='visual_identity_prompt',
            field=models.TextField(default="BLAST INFO & TECH produz stories verticais 9:16 sobre tecnologia, hardware, IA e cultura digital. A imagem deve ter energia editorial-tech, contraste alto, leitura imediata, clima premium, tipografia forte quando houver texto sobreposto, composicao limpa com um elemento principal, iluminacao dramatica, sem mockup de celular, sem marca d'agua, sem colagem confusa e sem excesso de elementos."),
        ),
        migrations.RunPython(migrate_visual_identity_prompt, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='brandguide',
            name='brand_summary',
        ),
        migrations.RemoveField(
            model_name='brandguide',
            name='visual_rules',
        ),
        migrations.AlterField(
            model_name='brandguide',
            name='copy_prompt_template',
            field=models.TextField(default='Voce esta criando um conceito de Instagram Story para {brand_name}.\n\nGuia visual da marca:\n{visual_identity_prompt}\n\nContexto do projeto:\n{project_context}\n\nPedido atual do editor:\n{change_request}\n\nResponda apenas em JSON valido com estas chaves:\n- headline\n- copy_text\n- visual_direction\n- image_prompt\n- generation_notes\n\nO copy_text deve ser conciso, pronto para um unico story, em portugues do Brasil.\n'),
        ),
        migrations.AlterField(
            model_name='brandguide',
            name='image_prompt_template',
            field=models.TextField(default="Crie a arte de um unico story vertical 9:16 para {brand_name}.\n\nGuia visual da marca:\n{visual_identity_prompt}\n\nDirecao visual aprovada:\n{visual_direction}\n\nPrompt base da imagem:\n{image_prompt}\n\nPedido atual do editor:\n{change_request}\n\nEvite marcas d'agua, mockups de celular, colagens confusas e texto pequeno ilegivel.\n"),
        ),
    ]
