# Generated by Django 5.2.13 on 2026-04-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('story_type', models.CharField(choices=[('news', 'News'), ('generic', 'Generic'), ('promotional', 'Promotional')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('concept_ready', 'Concept ready'), ('image_ready', 'Image ready'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('user_request', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_projects', to='news.newsarticle')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(editable=False)),
                ('change_request', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=220)),
                ('copy_text', models.TextField(blank=True)),
                ('visual_direction', models.TextField(blank=True)),
                ('image_prompt', models.TextField(blank=True)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('generation_notes', models.TextField(blank=True)),
                ('text_model', models.CharField(blank=True, max_length=120)),
                ('image_model', models.CharField(blank=True, max_length=120)),
                ('generated_image', models.FileField(blank=True, upload_to='stories/generated/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='stories.storyversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='stories.storyproject')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'version_number'), name='unique_story_version_per_project')],
            },
        ),
    ]
