# Generated by Django 5.2.13 on 2026-05-07 18:09

import django.db.models.deletion
import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkProjectBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('brand_mode', models.CharField(choices=[('blast', 'Blast'), ('beta', 'Beta')], default='blast', max_length=10)),
                ('raw_input', models.TextField(help_text='Cole as promoções com título, descrição e preço, mesmo com espaços irregulares.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('parsing', 'Parsing promotions'), ('creating', 'Creating projects'), ('generating', 'Generating assets'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('content_type', models.CharField(choices=[('news', 'News'), ('generic', 'Generic'), ('promotional', 'Promotional')], default='news', max_length=20)),
                ('brand_mode', models.CharField(choices=[('blast', 'Blast'), ('beta', 'Beta')], default='blast', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('concept_generating', 'Generating concept'), ('concept_ready', 'Concept ready'), ('image_generating', 'Generating images'), ('ready_for_selection', 'Ready for selection'), ('approved', 'Approved'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('target_format', models.CharField(choices=[('story', 'Story 1080x1920'), ('feed', 'Feed 1080x1350'), ('square', 'Square 1080x1080')], default='story', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('custom_brief', models.TextField(blank=True)),
                ('promotional_price', models.CharField(blank=True, max_length=80)),
                ('call_to_action', models.CharField(blank=True, max_length=140)),
                ('adjustment_request', models.TextField(blank=True, help_text='Único campo para pedir ajuste de conceito e das próximas imagens.')),
                ('requested_image_count', models.PositiveSmallIntegerField(default=2)),
                ('error_message', models.TextField(blank=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_projects', to='news.newsarticle')),
                ('bulk_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='stories.bulkprojectbatch')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('generation_kind', models.CharField(choices=[('initial', 'Initial'), ('revision', 'Revision'), ('bulk_auto', 'Bulk auto')], default='initial', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('instruction_snapshot', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('subheadline', models.CharField(blank=True, max_length=220)),
                ('body_text', models.TextField(blank=True)),
                ('price_text', models.CharField(blank=True, max_length=80)),
                ('call_to_action', models.CharField(blank=True, max_length=140)),
                ('visual_direction', models.TextField(blank=True)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('provider_response', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='stories.storyconcept')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='stories.storyproject')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='StoryImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_number', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('image_prompt_snapshot', models.TextField(blank=True)),
                ('provider_response', models.TextField(blank=True)),
                ('asset', models.FileField(blank=True, upload_to=stories.models.story_asset_upload_to)),
                ('asset_mime_type', models.CharField(blank=True, max_length=60)),
                ('error_message', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='stories.storyconcept')),
            ],
            options={
                'ordering': ['variant_number', '-created_at'],
                'unique_together': {('concept', 'variant_number')},
            },
        ),
    ]
