# Generated by Django 5.2.13 on 2026-05-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyproject',
            name='equipment_configuration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storyversion',
            name='caption_text',
            field=models.TextField(blank=True),
        ),
    ]
