# Generated by Django 5.2.13 on 2026-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_reconcile_legacy_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkprojectbatch',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('parsing', 'Recortando promoções'), ('creating', 'Criando projetos'), ('generating', 'Gerando artes'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyconcept',
            name='generation_kind',
            field=models.CharField(choices=[('initial', 'Inicial'), ('revision', 'Revisão'), ('bulk_auto', 'Massa automática')], default='initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyconcept',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('generating', 'Gerando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyimagevariant',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('generating', 'Gerando'), ('ready', 'Pronta'), ('failed', 'Falhou')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyproject',
            name='content_type',
            field=models.CharField(choices=[('news', 'Notícia'), ('generic', 'Institucional'), ('promotional', 'Promocional')], default='news', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('queued', 'Na fila'), ('concept_generating', 'Gerando conceito'), ('concept_ready', 'Conceito pronto'), ('image_generating', 'Gerando imagens'), ('ready_for_selection', 'Pronto para escolher'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('failed', 'Falhou')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='storyproject',
            name='target_format',
            field=models.CharField(choices=[('story', 'Story 1080x1920'), ('feed', 'Feed 1080x1350'), ('square', 'Quadrado 1080x1080')], default='story', max_length=20),
        ),
    ]
