# Generated by Django 5.2.13 on 2026-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_bulkprojectbatch_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyimagevariant',
            options={'ordering': ['target_format', 'variant_number', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='storyimagevariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storyimagevariant',
            name='target_format',
            field=models.CharField(choices=[('story', 'Story 1080x1920'), ('feed', 'Feed 1080x1350'), ('landscape', '1920x1080'), ('square', 'Quadrado 1080x1080')], default='feed', max_length=20),
        ),
        migrations.AddField(
            model_name='storyproject',
            name='target_formats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='storyproject',
            name='target_format',
            field=models.CharField(choices=[('story', 'Story 1080x1920'), ('feed', 'Feed 1080x1350'), ('landscape', '1920x1080'), ('square', 'Quadrado 1080x1080')], default='story', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='storyimagevariant',
            unique_together={('concept', 'target_format', 'variant_number')},
        ),
    ]
