# Generated by Django 5.2.13 on 2026-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_storyimagevariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyconcept',
            name='price_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storyproject',
            name='promotional_price',
            field=models.TextField(blank=True),
        ),
    ]
