# Generated by Django 5.2.13 on 2026-05-13 18:53

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_storyimagevariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimagevariant',
            name='asset',
            field=models.FileField(blank=True, max_length=255, upload_to=stories.models.story_asset_upload_to),
        ),
    ]
