# Generated by Django 5.2.13 on 2026-05-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_alter_storyimagevariant_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyconcept',
            name='social_caption',
            field=models.TextField(blank=True),
        ),
    ]
